<template>
  <div id="app">
    <div class="w3-theme-l5">
      <!-- Navbar -->
      <div class="w3-top">
        <div class="w3-bar w3-theme w3-left-align w3-large">
          <a class="w3-bar-item w3-button w3-hide-medium w3-hide-large w3-right w3-padding-large w3-hover-white w3-large w3-theme-d2" href="javascript:void(0);" onclick="openNav()"><i class="fa fa-bars"></i></a>
          <span class="w3-bar-item w3-padding-large w3-theme-d5"><i class="fa fa-file-text w3-margin-right"></i>The LT Project</span>
          <a v-on:click="currentPage = 0" href="#" v-bind:class="{ 'w3-theme-d3': currentPage === 0 }" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white" title="News"><i class="fa fa-cogs"></i> Main</a>
          <a v-on:click="currentPage = 1" href="#" v-bind:class="{ 'w3-theme-d3': currentPage === 1 }" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white" title="News"><i class="fa fa-users"></i> User Study</a>
          <a v-on:click="currentPage = 2" href="#" v-bind:class="{ 'w3-theme-d3': currentPage === 2 }" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white" title="News"><i class="fa fa-bar-chart"></i> Evaluation</a>
        </div>
      </div>

      <!-- Navbar on small screens -->
      <div id="navDemo" class="w3-bar-block w3-theme-d2 w3-hide w3-hide-large w3-hide-medium w3-large">
        <a href="#" class="w3-bar-item w3-button w3-padding-large">Link 1</a>
        <a href="#" class="w3-bar-item w3-button w3-padding-large">Link 2</a>
        <a href="#" class="w3-bar-item w3-button w3-padding-large">Link 3</a>
        <a href="#" class="w3-bar-item w3-button w3-padding-large">My Profile</a>
      </div>

      <!-- Page Container -->
      <div v-if="currentPage === 0" class="w3-container w3-content" style="max-width:1400px;margin-top:80px">
        <!-- The Grid -->
        <div class="w3-row">

          <!-- Middle Column -->
          <div class="w3-col">

            <!-- Search Container -->
            <div class="w3-row-padding">
              <div class="w3-col m12">
                <div class="w3-card w3-round w3-white">
                  <div class="w3-bar w3-theme-l3">
                    <button v-on:click="evalMode = 0" v-bind:class="{ 'w3-theme-l1': evalMode === 0 }" class="w3-bar-item w3-button w3-hover-white">Ask a question</button>
                    <button v-on:click="evalMode = 1" v-bind:class="{ 'w3-theme-l1': evalMode === 1 }" class="w3-bar-item w3-button w3-hover-white">Summarize your text</button>
                  </div>
                  <div class="w3-container w3-padding">
                    <h6 v-if="evalMode === 0" class="w3-opacity">Type your question:</h6>
                    <h6 v-if="evalMode === 1" class="w3-opacity">Provide Text to summarize:</h6>
                    <p v-if="evalMode === 0"><input v-model="input[currentPage][evalMode]" class="w3-border w3-padding" type="text" style="width:100%"></p>
                    <p v-if="evalMode === 1"><textarea v-model="input[currentPage][evalMode]" class="w3-border w3-padding" rows="5" style="width:100%"></textarea></p>
                    <p><select v-model="method[currentPage][evalMode]" class="w3-select w3-border w3-padding w3-white" name="option">
                      <option v-if="evalMode === 0" value="gold">Cheating</option>
                      <option value="textrank">TextRank</option>
                      <option value="network">Pointer-Generator Network</option>
                      <option value="bertsum">BertSum</option>
                    </select></p>
                    <button v-if="evalMode === 0" v-on:click="answerQuestion" type="button" class="w3-button w3-theme"><i class="fa fa-search"></i>  Search!</button>
                    <button v-if="evalMode === 1" v-on:click="answerText" type="button" class="w3-button w3-theme"><i class="fa fa-search"></i>  Summarize!</button>
                  </div>
                </div>
              </div>
            </div>
            <!-- END Search Container -->

            <!-- Article Answer Container -->
            <template v-if="evalMode === 0">
              <div v-if="summaries[currentPage][evalMode][currentMethod[currentPage][evalMode]][0] !== 'string'" class="w3-container w3-card w3-white w3-round w3-margin"><br>
                <span class="w3-right w3-opacity">generated by {{ currentMethod[currentPage][evalMode] }}</span>
                <h4>Short Instructions</h4>
                <hr class="w3-clear">
                <ul>
                  <li v-for="sentence in summaries[currentPage][evalMode][currentMethod[currentPage][evalMode]]">
                    {{ sentence }}
                  </li>
                </ul>
                <button v-on:click="showBetterSummary = !showBetterSummary" type="button" class="w3-button w3-theme-d2 w3-margin-bottom"><i class="fa fa-comment"></i> Summary not good? Provide a better one!</button>
                <div v-if="showBetterSummary" class="w3-container w3-card w3-theme-l4 w3-margin-bottom" style="margin-top:-16px">
                  <h4>Write a better summary</h4>
                  <p><textarea v-model="betterSummary" class="w3-border w3-padding" rows="5" style="width:100%"></textarea></p>
                  <p>{{betterSummaryLength}} / {{maxLength}}</p>
                  <button v-on:click="submitSummary" type="button" class="w3-button w3-theme-d2 w3-margin-bottom"><i class="fa fa-check"></i> Submit</button>
                </div>
              </div>

              <div v-if="text[currentPage][evalMode] !== 'string'" class="w3-container w3-card w3-white w3-round w3-margin"><br>
                <span class="w3-right w3-opacity">a WikiHow Article</span>
                <h4>Detailed Instructions</h4>
                <hr class="w3-clear">
                <p>{{text[currentPage][evalMode]}}</p>
              </div>
            </template>
            <!-- END Article Answer Container -->

            <!-- Text Answer Container -->
            <template v-if="evalMode === 1">
              <div v-if="summaries[currentPage][evalMode][currentMethod[currentPage][evalMode]][0] !== 'string'" class="w3-container w3-card w3-white w3-round w3-margin"><br>
                <span class="w3-right w3-opacity">generated by {{ currentMethod[currentPage][evalMode] }}</span>
                <h4>Summary</h4>
                <hr class="w3-clear">
                <ul>
                  <li v-for="sentence in summaries[currentPage][evalMode][currentMethod[currentPage][evalMode]]">
                    {{ sentence }}
                  </li>
                </ul>
              </div>
            </template>
            <!-- Text Answer Container -->

            <!-- End Middle Column -->
          </div>

          <!-- End Grid -->
        </div>

        <!-- End Page Container -->
      </div>

      <div v-if="currentPage === 1" class="w3-container w3-content" style="max-width:1400px;margin-top:80px">
        <!-- Input -->
        <div class="w3-row">

          <!-- Search Column -->
          <div class="w3-col">

            <div class="w3-row-padding">
              <div class="w3-col m12">
                <div class="w3-card w3-round w3-white">
                  <div class="w3-bar w3-theme-l3">
                    <button v-on:click="evalMode = 0" v-bind:class="{ 'w3-theme-l1': evalMode === 0 }" class="w3-bar-item w3-button w3-hover-white">Analyze a question</button>
                    <button v-on:click="evalMode = 1" v-bind:class="{ 'w3-theme-l1': evalMode === 1 }" class="w3-bar-item w3-button w3-hover-white">Analyze your own text</button>
                  </div>
                  <div class="w3-container w3-padding">
                    <h6 v-if="evalMode === 0" class="w3-opacity">Type your question:</h6>
                    <h6 v-if="evalMode === 1" class="w3-opacity">Provide Text to summarize:</h6>
                    <p v-if="evalMode === 0"><input v-model="input[currentPage][evalMode]" class="w3-border w3-padding" type="text" style="width:100%"></p>
                    <p v-if="evalMode === 1"><textarea v-model="input[currentPage][evalMode]" id="textarea-eval" class="w3-border w3-padding" rows="5" style="width:100%"></textarea></p>
                    <p><select v-model="method[currentPage][evalMode]" class="w3-select w3-border w3-padding w3-white" name="option">
                      <option value="all" selected>All Methods</option>
                      <option v-if="evalMode === 0" value="gold">Cheating</option>
                      <option value="textrank">TextRank</option>
                      <option value="network">Pointer-Generator Network</option>
                      <option value="bertsum">BertSum</option>
                    </select></p>
                    <p>
                      <template v-for="entity in allEntities">
                        <input v-on:change="updateHighlights" type="checkbox" :id="entity" :value="entity" v-model="checkedEntities"><label :for="entity"><span :class="entity" class="NER-NO-REMOVE NER">{{entity}}</span></label>
                      </template>
                    </p>
                    <button v-if="evalMode === 0" v-on:click="evaluateQuestion" id="button-evalquestion" type="button" class="w3-button w3-theme"><i class="fa fa-search"></i>  Analyze!</button>
                    <button v-if="evalMode === 1" v-on:click="evaluateText" id="button-evaltext" type="button" class="w3-button w3-theme"><i class="fa fa-search"></i>  Analyze!</button>
                  </div>
                </div>
              </div>
            </div>

            <!-- End Search Column -->
          </div>

          <!-- End Input -->
        </div>

        <!-- Evaluation-->
        <div class="w3-row">

          <!-- Left Column -->
          <div class="w3-col m6">

            <div v-if="currentMethod[currentPage][evalMode] === 'all'" v-for="summarizationMethod in allMethods" class="w3-row-padding wikihow-padding-top">
              <div v-if="!(summarizationMethod === 'gold' && evalMode === 1) && summaries[currentPage][evalMode][summarizationMethod][0] !== 'string'" class="w3-col m12">
                <div class="w3-card w3-round w3-white">
                  <div class="w3-container w3-padding">
                    <h6 class="w3-opacity">Summary {{summarizationMethod}}</h6>
                    <ul>
                      <li v-for="sentence in summaries[currentPage][evalMode][summarizationMethod]" v-html="sentence"></li>
                    </ul>
                    <p style="font-size:18px; margin-bottom: 0;">
                      <span class="w3-opacity">Submit a rating: </span>
                      <span v-on:click="rateMethod(summarizationMethod, 1)" @mouseover="hover[summarizationMethod]=ratingAllowed[summarizationMethod]?1:hover[summarizationMethod]" @mouseleave="hover[summarizationMethod]=ratingAllowed[summarizationMethod]?0:hover[summarizationMethod]" :class="{ checked: hover[summarizationMethod] >= 1 }" class="fa fa-star"></span>
                      <span v-on:click="rateMethod(summarizationMethod, 2)" @mouseover="hover[summarizationMethod]=ratingAllowed[summarizationMethod]?2:hover[summarizationMethod]" @mouseleave="hover[summarizationMethod]=ratingAllowed[summarizationMethod]?0:hover[summarizationMethod]" :class="{ checked: hover[summarizationMethod] >= 2 }" class="fa fa-star"></span>
                      <span v-on:click="rateMethod(summarizationMethod, 3)" @mouseover="hover[summarizationMethod]=ratingAllowed[summarizationMethod]?3:hover[summarizationMethod]" @mouseleave="hover[summarizationMethod]=ratingAllowed[summarizationMethod]?0:hover[summarizationMethod]" :class="{ checked: hover[summarizationMethod] >= 3 }" class="fa fa-star"></span>
                      <span v-on:click="rateMethod(summarizationMethod, 4)" @mouseover="hover[summarizationMethod]=ratingAllowed[summarizationMethod]?4:hover[summarizationMethod]" @mouseleave="hover[summarizationMethod]=ratingAllowed[summarizationMethod]?0:hover[summarizationMethod]" :class="{ checked: hover[summarizationMethod] >= 4 }" class="fa fa-star"></span>
                      <span v-on:click="rateMethod(summarizationMethod, 5)" @mouseover="hover[summarizationMethod]=ratingAllowed[summarizationMethod]?5:hover[summarizationMethod]" @mouseleave="hover[summarizationMethod]=ratingAllowed[summarizationMethod]?0:hover[summarizationMethod]" :class="{ checked: hover[summarizationMethod] >= 5 }" class="fa fa-star"></span>
                    </p>
                  </div>
                </div>
              </div>
            </div>

            <div v-if="currentMethod[currentPage][evalMode] !== 'all' && summaries[currentPage][evalMode][currentMethod[currentPage][evalMode]][0] !== 'string'" class="w3-row-padding wikihow-padding-top">
              <div class="w3-col m12">
                <div class="w3-card w3-round w3-white">
                  <div class="w3-container w3-padding">
                    <h6 class="w3-opacity">Summary {{currentMethod[currentPage][evalMode]}}</h6>
                    <ul>
                      <li v-for="sentence in summaries[currentPage][evalMode][currentMethod[currentPage][evalMode]]" v-html="sentence"></li>
                    </ul>
                    <p style="font-size:18px; margin-bottom: 0;">
                      <span class="w3-opacity">Submit a rating: </span>
                      <span v-on:click="rateMethod(currentMethod[currentPage][evalMode], 1)" @mouseover="hover[currentMethod[currentPage][evalMode]]=ratingAllowed[currentMethod[currentPage][evalMode]]?1:hover[currentMethod[currentPage][evalMode]]" @mouseleave="hover[currentMethod[currentPage][evalMode]]=ratingAllowed[currentMethod[currentPage][evalMode]]?0:hover[currentMethod[currentPage][evalMode]]" :class="{ checked: hover[currentMethod[currentPage][evalMode]] >= 1 }" class="fa fa-star"></span>
                      <span v-on:click="rateMethod(currentMethod[currentPage][evalMode], 2)" @mouseover="hover[currentMethod[currentPage][evalMode]]=ratingAllowed[currentMethod[currentPage][evalMode]]?2:hover[currentMethod[currentPage][evalMode]]" @mouseleave="hover[currentMethod[currentPage][evalMode]]=ratingAllowed[currentMethod[currentPage][evalMode]]?0:hover[currentMethod[currentPage][evalMode]]" :class="{ checked: hover[currentMethod[currentPage][evalMode]] >= 2 }" class="fa fa-star"></span>
                      <span v-on:click="rateMethod(currentMethod[currentPage][evalMode], 3)" @mouseover="hover[currentMethod[currentPage][evalMode]]=ratingAllowed[currentMethod[currentPage][evalMode]]?3:hover[currentMethod[currentPage][evalMode]]" @mouseleave="hover[currentMethod[currentPage][evalMode]]=ratingAllowed[currentMethod[currentPage][evalMode]]?0:hover[currentMethod[currentPage][evalMode]]" :class="{ checked: hover[currentMethod[currentPage][evalMode]] >= 3 }" class="fa fa-star"></span>
                      <span v-on:click="rateMethod(currentMethod[currentPage][evalMode], 4)" @mouseover="hover[currentMethod[currentPage][evalMode]]=ratingAllowed[currentMethod[currentPage][evalMode]]?4:hover[currentMethod[currentPage][evalMode]]" @mouseleave="hover[currentMethod[currentPage][evalMode]]=ratingAllowed[currentMethod[currentPage][evalMode]]?0:hover[currentMethod[currentPage][evalMode]]" :class="{ checked: hover[currentMethod[currentPage][evalMode]] >= 4 }" class="fa fa-star"></span>
                      <span v-on:click="rateMethod(currentMethod[currentPage][evalMode], 5)" @mouseover="hover[currentMethod[currentPage][evalMode]]=ratingAllowed[currentMethod[currentPage][evalMode]]?5:hover[currentMethod[currentPage][evalMode]]" @mouseleave="hover[currentMethod[currentPage][evalMode]]=ratingAllowed[currentMethod[currentPage][evalMode]]?0:hover[currentMethod[currentPage][evalMode]]" :class="{ checked: hover[currentMethod[currentPage][evalMode]] >= 5 }" class="fa fa-star"></span>
                    </p>
                  </div>
                </div>
              </div>
            </div>

          </div>

          <!-- Right Column -->
          <div class="w3-col m6">
            <div v-if="text[currentPage][evalMode] !== 'string'" class="w3-container w3-card w3-white w3-round w3-margin"><br>
              <span v-if="evalMode === 0" class="w3-right w3-opacity">a WikiHow Article</span>
              <span v-if="evalMode === 1" class="w3-right w3-opacity">a User Input Text</span>
              <h4 v-if="evalMode === 0">Original Article</h4>
              <h4 v-if="evalMode === 1">Original User Text</h4>
              <hr class="w3-clear">
              <p v-html="text[currentPage][evalMode]"></p>
            </div>
          </div>

        </div>

        <!-- End Page Container -->
      </div>

      <div v-if="currentPage === 2" class="w3-container w3-content" style="max-width:1400px;margin-top:80px">
        <!-- The Grid -->
        <div class="w3-row">

          <!-- Middle Column -->
          <div class="w3-col">

            <div v-for="summarizationMethod in allMethods" class="w3-row-padding wikihow-padding-top">
              <div class="w3-col m12">
                <div class="w3-card w3-round w3-white">
                  <div class="w3-container w3-padding">
                    <h4 class="w3-opacity">Evaluation of Method "{{summarizationMethod}}"</h4>
                    <line-chart :chart-data="chartData[summarizationMethod]" :options="chartOptions"></line-chart>
                    <button @click="fillData(summarizationMethod)">Refresh</button>
                  </div>
                </div>
              </div>
            </div>

            <!-- End Middle Column -->
          </div>

          <!-- End Grid -->
        </div>

        <!-- End Page Container -->
      </div>

      <br>

      <!-- Footer -->
      <footer class="w3-container w3-theme-d3 w3-padding-16">
        <h5>Footer</h5>
      </footer>
      <footer class="w3-container w3-theme-d5">
        <p>Powered by <a href="https://www.w3schools.com/w3css/default.asp" target="_blank">w3.css</a></p>
      </footer>
    </div>
  </div>
</template>

<script>
import LineChart from './components/LineChart';

require('@/assets/css/main.css');

export default {
  name: 'app',
  components: {
    LineChart,
  },
  data: function () {
    return {
      wikihowArticle: {
        "article": "string",
        "filename": "string",
        "score": 0,
        "summary": [
          "string",
        ],
        "summary_string": "string",
        "title": "string"
      },
      input: [[
        "how to ...",
        "string"
      ],[
        "how to ...",
        "string"
      ]],
      method: [[
        "textrank",
        "textrank"
      ],[
        "textrank",
        "textrank"
      ]],
      currentMethod: [[
        "textrank",
        "textrank"
      ],[
        "textrank",
        "textrank"
      ]],
      allMethods: ["textrank", "gold"],
      currentPage: 0,       // the actual body to show
      evalMode: 0,          // analyze question or own text?
      text: [[
        "string",
        "string"
      ],[
        "string",
        "string"
      ]],
      summaries: [[{
        "gold": [
          "string",
        ],
        "textrank": [
          "string",
        ],
        "network": [
          "string",
        ],
        "bertsum": [
          "string",
        ],
      }, {
        "gold": [
          "string",
        ],
        "textrank": [
          "string",
        ],
        "network": [
          "string",
        ],
        "bertsum": [
          "string",
        ],
      }],[{
        "gold": [
          "string",
        ],
        "textrank": [
          "string",
        ],
        "network": [
          "string",
        ],
        "bertsum": [
          "string",
        ],
      }, {
      "gold": [
        "string",
      ],
        "textrank": [
        "string",
      ],
        "network": [
        "string",
      ],
        "bertsum": [
        "string",
      ]}]],
      allEntities: [
        "PERSON",
        "LOC",
        "ORG",
        "MISC",
        "DATE",
        "TIME",
        "CARDINAL",
        "ORDINAL",
        "LAW",
        "MONEY",
        "PRODUCT",
        "GPE",
        "EVENT",
        "NORP",
        "FAC"
      ],
      checkedEntities: [
        "PERSON"
      ],
      hover: {
        "gold": 0,
        "textrank": 0,
        "network": 0,
        "bertsum": 0,
      },
      ratingAllowed: {
        "gold": true,
        "textrank": true,
        "network": true,
        "bertsum": true,
      },
      chartData: {
        "gold": null,
        "textrank": null,
        "network": null,
        "bertsum": null,
      },
      chartOptions: {
        responsive: false,
        scales: {
          xAxes: [{
            ticks: {
              beginAtZero: true,
              stepSize: 1,
            },
          }]
        }
      },
      summaryAllowed: {
        "gold": true,
        "textrank": true,
        "network": true,
        "bertsum": true,
      },
      betterSummary: "",
      showBetterSummary: false,
      maxLength: 512,
    }
  },
  computed: {
    // a computed getter
    betterSummaryLength: function () {
      return this.betterSummary.length
    }
  },
  watch: {
    currentPage: function (val) {
      console.log("Current Page changed! Page is " + val);

      // when page changes, update highlighted entities!
      setTimeout(() => {this.updateHighlights();}, 1);

      // // when page changes and method is all, change method to textrank
      // if(val === 0 && this.method === "all") {
      //   this.method = 'textrank';
      // }
      //
      // // when page changes and method is all, change method to textrank
      // if(val === 0 && this.currentMethod === "all") {
      //   this.currentMethod = 'textrank';
      // }

      if(val === 2) {
        for(let method of this.allMethods) {
          this.updateCharts(method);
        }
      }
    },
    evalMode: function (val) {
      console.log("Eval Mode changed! Mode is " + val);

      // when eval mode changes, update highlighted entities!
      setTimeout(() => {this.updateHighlights();}, 1);

      // when eval mode changes to text, and method is gold switch to textrank
      // if(val === 1 && this.method === "gold") {
      //   this.method = 'textrank';
      // }
      // if(val === 1 && this.currentMethod === "gold") {
      //   this.currentMethod = 'textrank';
      // }
    }
  },
  methods: {
    resetVars: function(page, mode, methods) {
      for(let method of methods) {
        this.summaries[page][mode][method] = ["string"];
      }
      this.text[page][mode] = "string";

      this.summaries = this.summaries.slice(0);
      this.text = this.text.slice(0);
    },
    updateHighlights: function() {
      // loop through all entities
      this.allEntities.forEach(entity => {
        // if entity is checked
        if(this.checkedEntities.indexOf(entity) >= 0) {
          Array.from(document.getElementsByClassName(entity)).forEach(element => {
            // activate visualization
            if(!element.classList.contains("NER")) {
              element.classList.add("NER");
            }
          });
        // if entity is not checked
        } else {
          Array.from(document.getElementsByClassName(entity)).forEach(element => {
            // deactivate visualization
            if(element.classList.contains("NER") && !element.classList.contains("NER-NO-REMOVE")) {
              element.classList.remove("NER");
            }
          });
        }
      });
    },
    fetchWikihowArticle: async function(question) {
      // get article from wikidata
      console.log("Fetching new WikiHow Artice");
      let data = await postData('http://localhost:8080/wikihowqa/articles', {
        "count": 1,
        "elasticindex": "wikihow",
        "topic": question
      });

      console.log("Success fetching new WikiHow Article");
      if(data.articles !== null && data.articles.length > 0) {
        this.wikihowArticle = data.articles[0];
        return data.articles[0];
      } else {
        throw new Error("WikiHow Article is empty!");
      }
    },
    fetchSummary: async function(text, method) {
      // get summary from the certain method
      console.log("Fetching new Summary with method " + method);
      let data = await postData('http://localhost:8080/wikihowqa/summarize', {
        "method": method,
        "text": text
      });

      console.log("Success fetching new Summary");
      console.log(data);
      if(data.summary !== undefined && data.summary !== null && data.summary.length > 5) {
        return data.summary;
      } else {
        throw new Error("Summary is empty!");
      }
    },
    fetchEntities: async function(text) {
      // get entities from text
      console.log("Fetching new Entities");
      let data = await postData('http://localhost:8080/wikihowqa/ner', {
        "text": text
      });

      console.log("Success fetching entities");
      if(data.entities !== null && data.entities.length > 0) {
        return data.entities;
      } else {
        throw new Error("Entities are empty!");
      }
    },
    fetchKeywords: async function(text) {
      // get entities from text
      console.log("Fetching Keywords");
      let data = await postData('http://localhost:8080/wikihowqa/keywords', {
        "count": 5,
        "lang": "eng",
        "text": text
      });

      console.log("Success fetching keywords");
      if(data.keywords !== null && data.keywords.length > 0) {
        return data.keywords;
      } else {
        throw new Error("Keywords are empty!");
      }
    },
    fetchRatings: async function(method) {
      console.log("Fetching Ratings for methd" + method);
      let data = await getData('http://localhost:8080/wikihowqa/ratings?method='+method);
      return data;
    },
    rateMethod: async function(method, rating) {
      if(!this.ratingAllowed[method])
        return;

      console.log("Rating Method " + method + " with " + rating + " stars");
      this.ratingAllowed[method] = false;
      let message = await postData('http://localhost:8080/wikihowqa/rate', {
        "method": method,
        "rating": rating,
        "title": this.wikihowArticle.title
      });
      console.log(message);
    },
    submitSummary: async function() {
      let currentMethod = this.currentMethod[0][0];

      if(!this.summaryAllowed[currentMethod])
        return;

      if(this.betterSummaryLength > this.maxLength)
        return;

      console.log("Submitting Summary for Article " + this.wikihowArticle.title + " and Method " + currentMethod);
      this.summaryAllowed[currentMethod] = false;
      let message = await postData('http://localhost:8080/wikihowqa/sum', {
        "method": currentMethod,
        "summary": this.betterSummary,
        "title": this.wikihowArticle.title
      });
      console.log(message);
    },
    answerQuestion: async function() {
      this.currentMethod[0][0] = this.method[0][0];
      let currentMethod = this.currentMethod[0][0];
      this.currentMethod = this.currentMethod.slice(0);

      this.resetVars(0, 0, [currentMethod]);

      // first fetch the wikihow article
      let article = undefined;
      try {
        article = await this.fetchWikihowArticle(this.input[0][0]);
        this.wikihowArticle = article;
        this.text[0][0] = article.article;
        this.text = this.text.slice(0);
      } catch(error) {
        console.log("An error occured during fetching the WikiHow article");
        console.log(error);
        return;
      }

      if(currentMethod !== 'gold') {
        // summarize article depending on the selected method
        try {
          let summary = await this.fetchSummary(article.article, currentMethod);
          this.summaries[0][0][currentMethod] = [summary];
        } catch(error) {
          console.log("An error occured during fetching the summary for the WikiHow article with the method " + currentMethod);
          console.log(error);
        }
      } else {
        this.summaries[0][0][currentMethod] = article.summary;
      }
      this.summaries = this.summaries.slice(0);
    },
    answerText: async function() {
      this.currentMethod[0][1] = this.method[0][1];
      let currentMethod = this.currentMethod[0][1];
      this.currentMethod = this.currentMethod.slice(0);

      this.resetVars(0, 1, [currentMethod]);

      // get input from textarea
      this.text[0][1] = this.input[0][1];
      let input = this.input[0][1];
      this.text = this.text.slice(0);


      if(input !== undefined && input !== null && input.length > 5) {
        // summarize article depending on the selected method
        try {
          let summary = await this.fetchSummary(input, currentMethod);
          this.summaries[0][1][currentMethod] = [summary];
        } catch(error) {
          console.log("An error occured during fetching the summary for the WikiHow article with the method " + currentMethod);
          console.log(error);
        }
      }
      this.summaries = this.summaries.slice(0);
    },
    evaluateQuestion: async function() {
      this.currentMethod[1][0] = this.method[1][0];
      let currentMethod = this.currentMethod[1][0];
      this.currentMethod = this.currentMethod.slice(0);

      if(currentMethod === 'all')
        this.resetVars(1, 0, this.allMethods);
      else
        this.resetVars(1, 0, [currentMethod]);

      // first fetch the wikihow article
      let article = undefined;
      try {
        article = await this.fetchWikihowArticle(this.input[1][0]);
        this.text[1][0] = article.article;
        this.text = this.text.slice(0);
      } catch(error) {
        console.log("An error occured during fetching the WikiHow article");
        console.log(error);
        return;
      }

      console.log("Processing WikiHow article");

      // Get Named Entities, Get Keywords, Then visualize them
      this.text[1][0] = await this.processEntitiesAndKeywords(this.text[1][0]);
      this.text = this.text.slice(0);

      // summarize article
      // depending on selection, use all methods
      if(currentMethod === 'all') {
        for(let method of this.allMethods) {
          if(method === 'gold') {
            let summary = article.summary.join(" ");
            let processedSummary = await this.processEntitiesAndKeywords(summary);
            this.summaries[1][0][method] = [processedSummary];
          } else {
            // Get Summary
            let summary = await this.generateSummary(article.article, method);
            this.summaries[1][0][method] = [summary];
          }
        }
      // the gold method
      } else if (currentMethod === 'gold') {
        let summary = article.summary.join(" ");
        let processedSummary = await this.processEntitiesAndKeywords(summary);
        this.summaries[1][0][currentMethod] = [processedSummary];
      // or just the selected method
      } else {
        // Get Summary
        let summary = await this.generateSummary(article.article, currentMethod);
        this.summaries[1][0][currentMethod] = [summary];
      }
      this.summaries = this.summaries.slice(0);
    },
    evaluateText: async function() {
      this.currentMethod[1][1] = this.method[1][1];
      let currentMethod = this.currentMethod[1][1];
      this.currentMethod = this.currentMethod.slice(0);

      if(currentMethod === 'all')
        this.resetVars(1, 1, this.allMethods);
      else
        this.resetVars(1, 1, [currentMethod]);

      // get input from textarea
      this.text[1][1] = this.input[1][1];
      let input = this.input[1][1];
      this.text = this.text.slice(0);

      // then process it
      if(input !== undefined && input !== null && input.length > 5) {
        console.log("Processing text");

        // Get Named Entities, Get Keywords, Then visualize them
        this.text[1][1] = await this.processEntitiesAndKeywords(input);
        this.text = this.text.slice(0);

        // summarize input
        // depending on selection, use all methods
        if(currentMethod === 'all') {
          for(let method of this.allMethods) {
            if(method !== 'gold') {
              let summary = await this.generateSummary(input, method);
              this.summaries[1][1][method] = [summary];
            }
          }
          // or just the selected method
        } else {
          let summary = await this.generateSummary(input, currentMethod);
          this.summaries[1][1][currentMethod] = [summary];
        }
      }
      this.summaries = this.summaries.slice(0);
    },
    hasQuestionChanged() {
      if(this.oldQuestion !== this.question) {
        this.oldQuestion = this.question;
        return true;
      }
      return false;
    },
    hasTextChanged() {
      if(this.oldText !== this.text) {
        this.oldText = this.text;
        return true;
      }
      return false;
    },
    hasMethodChanged() {
      if(this.oldMethod !== this.method) {
        this.oldMethod = this.method;
        return true;
      }
      return false;
    },
    visualizeEntitiesAndKeywords: function(text, entities, keywords) {
      console.log("Visualizing Entities and Keywords");
      if(entities === undefined && keywords === undefined) {
        return;
      }

      console.log(entities);
      console.log(keywords);

      // Collect all text replacements
      let replacements = [];

      if(entities !== undefined) {
        entities.forEach((element) => {
          let spanClass = this.checkedEntities.indexOf(element.label) >= 0 ? "NER " + element.label : element.label;
          let spanStart = "<span class='"+ spanClass + "'>";
          let spanEnd = " <b class='NER-LABEL'>"+element.label+"</b></span>";

          replacements.push([element.start, spanStart]);
          replacements.push([element.end, spanEnd]);
        });
      }

      if(keywords !== undefined) {
        keywords.forEach((element) => {
          // if(!options[element[1]])
          //   return;

          let match;
          let re = new RegExp(element.word,"g");
          while ((match = re.exec(text)) != null) {
            let spanStart = "<span class='KEYWORD'>";
            let spanEnd = "</span>";

            replacements.push([match.index, spanStart]);
            replacements.push([match.index + element.word.length, spanEnd]);
          }
        });
      }

      // Sort the replacements
      replacements = replacements.sort((a, b) => a[0] - b[0]);

      // Insert the replacements
      let newText = text;
      let offset = 0;
      replacements.forEach(function (element) {
        newText = text.slice(0, element[0] + offset) + element[1] + text.slice(element[0] + offset, text.length);
        text = newText;
        offset = offset + element[1].length;
      });

      return text;
    },
    processEntitiesAndKeywords: async function(text) {
      let entities = undefined;
      let keywords = undefined;
      try {
        entities = await this.fetchEntities(text);
      } catch(error) {
        console.log("An error occured during fetching the entities for the WikiHow article");
        console.log(error);
      }
      try {
        keywords = await this.fetchKeywords(text);
      } catch(error) {
        console.log("An error occured during fetching the keywords for the WikiHow article");
        console.log(error);
      }
      return this.visualizeEntitiesAndKeywords(text, entities, keywords);
    },
    generateSummary: async function(text, method) {
      try {
        let summary = await this.fetchSummary(text, method);
        let processedSummary = await this.processEntitiesAndKeywords(summary);
        return processedSummary;
      } catch(error) {
        console.log("An error occured during fetching the summary for the WikiHow article with the method " + method);
        console.log(error);
      }
    },
    updateCharts: async function(method) {
      let ratings = await this.fetchRatings(method);
      console.log(ratings);

      this.chartData[method] = {
        labels: ["1 Star", "2 Stars", "3 Stars", "4 Stars", "5 Stars"],
        datasets: [
          {
            label: 'Method ' + method,
            backgroundColor: ["red", "blue", "green", "blue", "red"],
            borderColor: ["black", "grey", "black", "grey", "black"],
            data: ratings,
            borderWidth: 5,
          },
        ]
      }
    },
  },
  created() {
    // Execute methods on create
  },
};

function getData(url = '', data = {}) {
  // Default options are marked with *
  return fetch(url, {
    method: 'GET', // *GET, POST, PUT, DELETE, etc.
    mode: 'cors', // no-cors, cors, *same-origin
    cache: 'no-cache', // *default, no-cache, reload, force-cache, only-if-cached
    credentials: 'same-origin', // include, *same-origin, omit
    headers: {
      'Content-Type': 'application/json',
      // 'Content-Type': 'application/x-www-form-urlencoded',
    },
    redirect: 'follow', // manual, *follow, error
    referrer: 'no-referrer', // no-referrer, *client
  })
    .then(response => response.json()); // parses JSON response into native JavaScript objects
}

function postData(url = '', data = {}) {
  // Default options are marked with *
  return fetch(url, {
    method: 'POST', // *GET, POST, PUT, DELETE, etc.
    mode: 'cors', // no-cors, cors, *same-origin
    cache: 'no-cache', // *default, no-cache, reload, force-cache, only-if-cached
    credentials: 'same-origin', // include, *same-origin, omit
    headers: {
      'Content-Type': 'application/json',
      // 'Content-Type': 'application/x-www-form-urlencoded',
    },
    redirect: 'follow', // manual, *follow, error
    referrer: 'no-referrer', // no-referrer, *client
    body: JSON.stringify(data), // body data type must match "Content-Type" header
  })
    .then(response => response.json()); // parses JSON response into native JavaScript objects
}

// Used to toggle the menu on smaller screens when clicking on the menu button
function openNav() {
  var x = document.getElementById("navDemo");
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
  } else {
    x.className = x.className.replace(" w3-show", "");
  }
}
</script>

<style>
  @import "https://www.w3schools.com/w3css/4/w3.css";
  @import "https://www.w3schools.com/lib/w3-theme-light-green.css";
  @import "https://fonts.googleapis.com/css?family=Open+Sans'";
  @import "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css";
  html, body, h1, h2, h3, h4, h5 {font-family: "Open Sans", sans-serif}
  .wikihow-padding-top {
    padding-top: 16px;
  }
</style>
